# Generated by Django 2.0.3 on 2018-03-15 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specializations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_score', models.IntegerField(db_index=True, default=0)),
                ('num_vote_up', models.PositiveIntegerField(db_index=True, default=0)),
                ('num_vote_down', models.PositiveIntegerField(db_index=True, default=0)),
                ('build_name', models.CharField(max_length=50, verbose_name='Build Name')),
                ('build_description', models.TextField(max_length=200, verbose_name='Build Description')),
                ('build_upload_date', models.DateField(auto_now_add=True, verbose_name='Build upload date')),
                ('build_last_edit_date', models.DateField(auto_now=True, verbose_name="Build's last edit date")),
                ('gw2skills_link', models.URLField(verbose_name='Link to build on gw2skills.net')),
                ('profession', models.CharField(max_length=15, verbose_name='Profession')),
                ('spec1', models.IntegerField(default=0, verbose_name='Specialization 1')),
                ('minor1_1', models.IntegerField(default=0, verbose_name='Spec.1 Minor Adept Trait')),
                ('major1_1', models.IntegerField(default=0, verbose_name='Spec.1 Major Adept Trait')),
                ('minor1_2', models.IntegerField(default=0, verbose_name='Spec.1 Minor Master Trait')),
                ('major1_2', models.IntegerField(default=0, verbose_name='Spec.1 Major Master Trait')),
                ('minor1_3', models.IntegerField(default=0, verbose_name='Spec.1 Minor Grandmaster Trait')),
                ('major1_3', models.IntegerField(default=0, verbose_name='Spec.1 Major Grandmaster Trait')),
                ('spec2', models.IntegerField(default=0, verbose_name='Specialization 2')),
                ('minor2_1', models.IntegerField(default=0, verbose_name='Spec.2 Minor Adept Trait')),
                ('major2_1', models.IntegerField(default=0, verbose_name='Spec.2 Major Adept Trait')),
                ('minor2_2', models.IntegerField(default=0, verbose_name='Spec.2 Minor Master Trait')),
                ('major2_2', models.IntegerField(default=0, verbose_name='Spec.2 Major Master Trait')),
                ('minor2_3', models.IntegerField(default=0, verbose_name='Spec.2 Minor Grandmaster Trait')),
                ('major2_3', models.IntegerField(default=0, verbose_name='Spec.2 Major Grandmaster Trait')),
                ('spec3', models.IntegerField(default=0, verbose_name='Specialization 3')),
                ('minor3_1', models.IntegerField(default=0, verbose_name='Spec.3 Minor Adept Trait')),
                ('major3_1', models.IntegerField(default=0, verbose_name='Spec.3 Major Adept Trait')),
                ('minor3_2', models.IntegerField(default=0, verbose_name='Spec.3 Minor Master Trait')),
                ('major3_2', models.IntegerField(default=0, verbose_name='Spec.3 Major Master Trait')),
                ('minor3_3', models.IntegerField(default=0, verbose_name='Spec.3 Minor Grandmaster Trait')),
                ('major3_3', models.IntegerField(default=0, verbose_name='Spec.3 Major Grandmaster Trait')),
                ('skill1', models.IntegerField(default=0, verbose_name='Weapon Skill 1')),
                ('skill2', models.IntegerField(default=0, verbose_name='Weapon Skill 2')),
                ('skill3', models.IntegerField(default=0, verbose_name='Weapon Skill 3')),
                ('skill4', models.IntegerField(default=0, verbose_name='Weapon Skill 4')),
                ('skill5', models.IntegerField(default=0, verbose_name='Weapon Skill 5')),
                ('skill6', models.IntegerField(default=0, verbose_name='Healing Skill')),
                ('skill7', models.IntegerField(default=0, verbose_name='Utility Skill 1')),
                ('skill8', models.IntegerField(default=0, verbose_name='Utility Skill 2')),
                ('skill9', models.IntegerField(default=0, verbose_name='Utility Skill 3')),
                ('skill0', models.IntegerField(default=0, verbose_name='Elite Skill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
