# Generated by Django 2.0.3 on 2018-03-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_auto_20180317_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Specializations',
            new_name='Build',
        ),
    ]
